import type { BinStation } from "@/contexts/app-context"

// All bin stations placed across Ulaanbaatar, Mongolia
export const BIN_STATIONS: BinStation[] = [
  {
    id: "station-1",
    name: "Sukhbaatar Square Hub",
    address: "Sukhbaatar Square, Chingeltei",
    distance: 80,
    lat: 47.9184,
    lng: 106.9177,
    compartments: ["plastic", "paper", "metal", "general"],
  },
  {
    id: "station-2",
    name: "State Department Store",
    address: "Peace Ave 44, Chingeltei",
    distance: 210,
    lat: 47.9121,
    lng: 106.9154,
    compartments: ["plastic", "paper", "metal", "general"],
  },
  {
    id: "station-3",
    name: "Narantuul Market Station",
    address: "Narantuul Market, Bayanzurkh",
    distance: 950,
    lat: 47.9074,
    lng: 106.9431,
    compartments: ["plastic", "paper", "metal", "general"],
  },
  {
    id: "station-4",
    name: "Zaisan Hill Eco Point",
    address: "Zaisan Memorial, Khan-Uul",
    distance: 1400,
    lat: 47.8803,
    lng: 106.9098,
    compartments: ["plastic", "paper", "metal", "general"],
  },
  {
    id: "station-5",
    name: "National University Station",
    address: "Ikh Toiruu 1, Sukhbaatar",
    distance: 390,
    lat: 47.9207,
    lng: 106.9255,
    compartments: ["plastic", "paper", "metal", "general"],
  },
  {
    id: "station-6",
    name: "Gandan Monastery Bin",
    address: "Gandan Monastery, Sukhbaatar",
    distance: 680,
    lat: 47.9208,
    lng: 106.8994,
    compartments: ["plastic", "paper", "metal", "general"],
  },
  {
    id: "station-7",
    name: "Bayangol District Hub",
    address: "Bayangol District Center",
    distance: 1100,
    lat: 47.9051,
    lng: 106.8782,
    compartments: ["plastic", "paper", "metal", "general"],
  },
  {
    id: "station-8",
    name: "Chinggis Khaan Museum",
    address: "Khudaldaany Gudamj, Chingeltei",
    distance: 530,
    lat: 47.9148,
    lng: 106.9298,
    compartments: ["plastic", "paper", "metal", "general"],
  },
  {
    id: "station-9",
    name: "Central Post Office Area",
    address: "Peace Ave 57, Chingeltei",
    distance: 170,
    lat: 47.9099,
    lng: 106.9163,
    compartments: ["plastic", "paper", "metal", "general"],
  },
  {
    id: "station-10",
    name: "Naran Plaza Station",
    address: "Naran Plaza Mall, Sukhbaatar",
    distance: 760,
    lat: 47.9231,
    lng: 106.9177,
    compartments: ["plastic", "paper", "metal", "general"],
  },
]
